# Generated by Django 4.1.1 on 2023-04-05 23:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0004_rename_care_title_car_car_title_alter_car_year'),
    ]

    operations = [
        migrations.RenameField(
            model_name='car',
            old_name='car_title',
            new_name='care_title',
        ),
    ]
